#:kivy 2.0.0

<TitleScreen>:
    name: 'title'
	canvas.before:
        Color: 
            rgba: 0.5, 0.5, 0.5, 1 #color of background
        Rectangle:
            source:'source/title_game.jpg'
            pos: self.pos
            size: self.size

<GameScreen>:
    name: 'game'
    canvas.before:
        Color: 
            rgba: 0.5, 0.5, 0.5, 1 #color of background
        Rectangle:
            source:'source/game_background.jpg'
            pos: self.pos
            size: self.size
